## Load/Clean Data

Sources: 

https://www.basketball-reference.com/leagues/NBA_2024_per_game.html

https://www.basketball-reference.com/players/a/antetgi01/gamelog/2024

In [38]:
import pandas as pd

url = "https://www.basketball-reference.com/players/a/antetgi01/gamelog/2024"   # Giannis 23-24 season game-by-game stats

html = pd.read_html(url, header=0)
df = html[7]                              # selects desired table on website page
df

,Rk,G,Date,Age,Tm,Unnamed: 5,Opp,Unnamed: 7,GS,MP,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-
0,1,1,2023-10-26,28-324,MIL,NaN,PHI,W (+1),1,35:07,...,8,12,3,2,2,7,4,23,12.0,-13
1,2,2,2023-10-29,28-327,MIL,NaN,ATL,L (-17),1,29:28,...,6,11,3,1,2,3,2,26,25.0,-11
2,3,3,2023-10-30,28-328,MIL,NaN,MIA,W (+8),1,31:51,...,6,7,2,0,1,2,3,33,23.3,+18
3,4,4,2023-11-01,28-330,MIL,@,TOR,L (-19),1,27:41,...,1,4,2,1,0,3,3,16,9.7,-10
4,5,5,2023-11-03,28-332,MIL,NaN,NYK,W (+5),1,35:47,...,7,8,6,0,1,7,3,22,14.5,+13
5,6,6,2023-11-06,28-335,MIL,@,BRK,W (+4),1,35:15,...,10,12,3,1,2,3,1,36,28.2,+15
6,7,7,2023-11-08,28-337,MIL,NaN,DET,W (+2),1,21:52,...,9,9,5,0,3,1,1,15,11.9,+5
7,8,8,2023-11-09,28-338,MIL,@,IND,L (-2),1,36:29,...,10,12,3,0,0,8,4,54,40.2,+6
8,9,9,2023-11-11,28-340,MIL,@,ORL,L (-15),1,36:39,...,8,10,7,4,2,6,4,35,29.3,-11
9,10,10,2023-11-13,28-342,MIL,NaN,CHI,W (+9),1,34:42,...,8,11,2,0,0,3,4,35,23.7,+13
10,11,NaN,2023-11-15,28-344,MIL,@,TOR,W (+16),Inactive,Inactive,...,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive
11,12,11,2023-11-17,28-346,MIL,@,CHO,W (+31),1,28:10,...,8,8,9,1,0,4,5,16,13.9,+6
12,13,12,2023-11-18,28-347,MIL,NaN,DAL,W (+7),1,37:51,...,13,15,7,2,1,3,3,40,36.9,-7
13,14,13,2023-11-20,28-349,MIL,@,WAS,W (+13),1,33:54,...,7,13,8,1,1,5,2,42,40.1,+10
14,15,14,2023-11-22,28-351,MIL,@,BOS,L (-3),1,36:30,...,10,13,5,2,0,3,4,21,14.6,+6
15,16,15,2023-11-24,28-353,MIL,NaN,WAS,W (+3),1,37:13,...,6,9,3,3,1,3,2,31,26.8,-10
16,17,16,2023-11-26,28-355,MIL,NaN,POR,W (+6),1,38:49,...,10,16,6,1,3,4,5,33,28.4,+9
17,18,17,2023-11-28,28-357,MIL,@,MIA,W (+7),1,39:30,...,8,10,5,3,1,4,3,33,30.8,+18
18,19,18,2023-11-30,28-359,MIL,@,CHI,L (-7),1,38:52,...,8,14,5,2,5,5,5,26,27.1,-8
19,20,19,2023-12-02,28-361,MIL,NaN,ATL,W (+11),1,36:19,...,9,11,10,2,1,5,1,32,31.6,+8
20,Rk,G,Date,Age,Tm,NaN,Opp,NaN,GS,MP,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-
21,21,20,2023-12-05,28-364,MIL,NaN,NYK,W (+24),1,33:49,...,5,8,10,3,0,4,3,35,32.0,+19
22,22,21,2023-12-07,29-001,MIL,NaN,IND,L (-9),1,40:30,...,9,10,2,0,2,1,3,37,32.1,-5
23,23,22,2023-12-11,29-005,MIL,NaN,CHI,W (+4),1,40:57,...,11,12,6,2,0,2,2,32,32.3,+13
24,24,23,2023-12-13,29-007,MIL,NaN,IND,W (+14),1,37:13,...,11,14,3,4,1,4,1,64,57.0,+29
25,25,24,2023-12-16,29-010,MIL,NaN,DET,W (+32),1,25:47,...,7,8,6,1,0,0,1,22,24.1,+22
26,26,25,2023-12-17,29-011,MIL,NaN,HOU,W (+9),1,39:10,...,11,17,3,0,0,6,3,26,14.6,+11
27,27,26,2023-12-19,29-013,MIL,NaN,SAS,W (+13),1,33:36,...,12,14,16,2,1,3,1,11,18.5,+13
28,28,27,2023-12-21,29-015,MIL,NaN,ORL,W (+4),1,37:18,...,8,10,6,0,2,5,4,37,25.1,+9
29,29,28,2023-12-23,29-017,MIL,@,NYK,W (+19),1,32:21,...,5,7,7,1,1,5,4,28,22.6,+3
30,30,29,2023-12-25,29-019,MIL,@,NYK,L (-7),1,38:39,...,8,13,6,1,2,2,4,32,27.7,-5
31,31,30,2023-12-27,29-021,MIL,@,BRK,W (+22),1,30:27,...,8,10,8,0,2,2,2,32,33.6,+8
32,32,31,2023-12-29,29-023,MIL,@,CLE,W (+8),1,36:34,...,14,16,5,1,0,3,2,34,30.1,+12
33,33,32,2024-01-01,29-026,MIL,NaN,IND,L (-9),1,36:55,...,15,18,11,1,2,4,3,30,30.7,+3
34,34,33,2024-01-03,29-028,MIL,@,IND,L (-12),1,35:43,...,11,11,8,3,1,3,2,26,27.3,-12
35,35,34,2024-01-04,29-029,MIL,@,SAS,W (+4),1,39:30,...,11,14,7,2,1,1,3,44,42.0,+11
36,36,35,2024-01-06,29-031,MIL,@,HOU,L (-4),1,38:56,...,14,17,2,0,1,2,4,48,39.3,-1

**Data cleaning**

In [39]:
import numpy as np

df = df.drop(df[df.Date == "Date"].index)                    # deletes repeating headers in content
df = df.drop(df[df.GS == "Inactive"].index)                  # deletes games where he was inactive
df = df.drop(columns=["Date", "Unnamed: 7", "Age", "GS", "+/-"])            # deletes useless columns
df.rename(columns={'Unnamed: 5': 'Home'}, inplace=True)      # renames "Unnamed 5" to "Home"
df['Home'].replace({np.nan: 'Yes', '@': 'No'}, inplace=True) # reformats "Home" values
df['NextPTS'] = df['PTS'].shift(-1)                          # Shift 'PTS' values down by one and assign to 'NextPTS'
df.fillna(0, inplace=True)                                   # replaces NaN with 0
df = df.reset_index(drop=True)                               # resets index

df

,Rk,G,Tm,Home,Opp,MP,FG,FGA,FG%,3P,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,NextPTS
0,1,1,MIL,Yes,PHI,35:07,10,21,.476,0,...,8,12,3,2,2,7,4,23,12.0,26
1,2,2,MIL,Yes,ATL,29:28,9,14,.643,0,...,6,11,3,1,2,3,2,26,25.0,33
2,3,3,MIL,Yes,MIA,31:51,12,21,.571,1,...,6,7,2,0,1,2,3,33,23.3,16
3,4,4,MIL,No,TOR,27:41,5,11,.455,0,...,1,4,2,1,0,3,3,16,9.7,22
4,5,5,MIL,Yes,NYK,35:47,6,10,.600,3,...,7,8,6,0,1,7,3,22,14.5,36
5,6,6,MIL,No,BRK,35:15,15,27,.556,1,...,10,12,3,1,2,3,1,36,28.2,15
6,7,7,MIL,Yes,DET,21:52,6,16,.375,0,...,9,9,5,0,3,1,1,15,11.9,54
7,8,8,MIL,No,IND,36:29,19,25,.760,0,...,10,12,3,0,0,8,4,54,40.2,35
8,9,9,MIL,No,ORL,36:39,15,22,.682,0,...,8,10,7,4,2,6,4,35,29.3,35
9,10,10,MIL,Yes,CHI,34:42,13,22,.591,1,...,8,11,2,0,0,3,4,35,23.7,16
10,12,11,MIL,No,CHO,28:10,6,10,.600,0,...,8,8,9,1,0,4,5,16,13.9,40
11,13,12,MIL,Yes,DAL,37:51,18,26,.692,1,...,13,15,7,2,1,3,3,40,36.9,42
12,14,13,MIL,No,WAS,33:54,20,23,.870,0,...,7,13,8,1,1,5,2,42,40.1,21
13,15,14,MIL,No,BOS,36:30,7,20,.350,0,...,10,13,5,2,0,3,4,21,14.6,31
14,16,15,MIL,Yes,WAS,37:13,11,19,.579,0,...,6,9,3,3,1,3,2,31,26.8,33
15,17,16,MIL,Yes,POR,38:49,11,21,.524,0,...,10,16,6,1,3,4,5,33,28.4,33
16,18,17,MIL,No,MIA,39:30,11,16,.688,1,...,8,10,5,3,1,4,3,33,30.8,26
17,19,18,MIL,No,CHI,38:52,11,17,.647,0,...,8,14,5,2,5,5,5,26,27.1,32
18,20,19,MIL,Yes,ATL,36:19,14,20,.700,0,...,9,11,10,2,1,5,1,32,31.6,35
19,21,20,MIL,Yes,NYK,33:49,15,22,.682,1,...,5,8,10,3,0,4,3,35,32.0,37
20,22,21,MIL,Yes,IND,40:30,13,19,.684,0,...,9,10,2,0,2,1,3,37,32.1,32
21,23,22,MIL,Yes,CHI,40:57,9,13,.692,0,...,11,12,6,2,0,2,2,32,32.3,64
22,24,23,MIL,Yes,IND,37:13,20,28,.714,0,...,11,14,3,4,1,4,1,64,57.0,22
23,25,24,MIL,Yes,DET,25:47,7,9,.778,0,...,7,8,6,1,0,0,1,22,24.1,26
24,26,25,MIL,Yes,HOU,39:10,10,22,.455,1,...,11,17,3,0,0,6,3,26,14.6,11
25,27,26,MIL,Yes,SAS,33:36,4,12,.333,0,...,12,14,16,2,1,3,1,11,18.5,37
26,28,27,MIL,Yes,ORL,37:18,11,25,.440,0,...,8,10,6,0,2,5,4,37,25.1,28
27,29,28,MIL,No,NYK,32:21,11,17,.647,0,...,5,7,7,1,1,5,4,28,22.6,32
28,30,29,MIL,No,NYK,38:39,13,24,.542,1,...,8,13,6,1,2,2,4,32,27.7,32
29,31,30,MIL,No,BRK,30:27,10,12,.833,0,...,8,10,8,0,2,2,2,32,33.6,34
30,32,31,MIL,No,CLE,36:34,14,22,.636,0,...,14,16,5,1,0,3,2,34,30.1,30
31,33,32,MIL,Yes,IND,36:55,11,20,.550,0,...,15,18,11,1,2,4,3,30,30.7,26
32,34,33,MIL,No,IND,35:43,8,13,.615,1,...,11,11,8,3,1,3,2,26,27.3,44
33,35,34,MIL,No,SAS,39:30,19,28,.679,2,...,11,14,7,2,1,1,3,44,42.0,48
34,36,35,MIL,No,HOU,38:56,16,25,.640,1,...,14,17,2,0,1,2,4,48,39.3,0

In [40]:
print(df.dtypes)

Rk         object
G          object
Tm         object
Home       object
Opp        object
MP         object
FG         object
FGA        object
FG%        object
3P         object
3PA        object
3P%        object
FT         object
FTA        object
FT%        object
ORB        object
DRB        object
TRB        object
AST        object
STL        object
BLK        object
TOV        object
PF         object
PTS        object
GmSc       object
NextPTS    object
dtype: object

In [41]:
# Convert multiple columns to numeric
columns_to_convert = ['G', 'FG', 'FGA', '3P', '3PA', 'FT', 
                      'FTA', 'ORB', 'DRB', 'TRB', 'AST', 
                      'STL', 'BLK', 'TOV', 'PF', 'PTS', 'NextPTS']

for column in columns_to_convert:
    df[column] = pd.to_numeric(df[column], errors='coerce').fillna(0)

print(df.dtypes)

Rk         object
G           int64
Tm         object
Home       object
Opp        object
MP         object
FG          int64
FGA         int64
FG%        object
3P          int64
3PA         int64
3P%        object
FT          int64
FTA         int64
FT%        object
ORB         int64
DRB         int64
TRB         int64
AST         int64
STL         int64
BLK         int64
TOV         int64
PF          int64
PTS         int64
GmSc       object
NextPTS     int64
dtype: object

In [42]:
df

,Rk,G,Tm,Home,Opp,MP,FG,FGA,FG%,3P,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,NextPTS
0,1,1,MIL,Yes,PHI,35:07,10,21,.476,0,...,8,12,3,2,2,7,4,23,12.0,26
1,2,2,MIL,Yes,ATL,29:28,9,14,.643,0,...,6,11,3,1,2,3,2,26,25.0,33
2,3,3,MIL,Yes,MIA,31:51,12,21,.571,1,...,6,7,2,0,1,2,3,33,23.3,16
3,4,4,MIL,No,TOR,27:41,5,11,.455,0,...,1,4,2,1,0,3,3,16,9.7,22
4,5,5,MIL,Yes,NYK,35:47,6,10,.600,3,...,7,8,6,0,1,7,3,22,14.5,36
5,6,6,MIL,No,BRK,35:15,15,27,.556,1,...,10,12,3,1,2,3,1,36,28.2,15
6,7,7,MIL,Yes,DET,21:52,6,16,.375,0,...,9,9,5,0,3,1,1,15,11.9,54
7,8,8,MIL,No,IND,36:29,19,25,.760,0,...,10,12,3,0,0,8,4,54,40.2,35
8,9,9,MIL,No,ORL,36:39,15,22,.682,0,...,8,10,7,4,2,6,4,35,29.3,35
9,10,10,MIL,Yes,CHI,34:42,13,22,.591,1,...,8,11,2,0,0,3,4,35,23.7,16
10,12,11,MIL,No,CHO,28:10,6,10,.600,0,...,8,8,9,1,0,4,5,16,13.9,40
11,13,12,MIL,Yes,DAL,37:51,18,26,.692,1,...,13,15,7,2,1,3,3,40,36.9,42
12,14,13,MIL,No,WAS,33:54,20,23,.870,0,...,7,13,8,1,1,5,2,42,40.1,21
13,15,14,MIL,No,BOS,36:30,7,20,.350,0,...,10,13,5,2,0,3,4,21,14.6,31
14,16,15,MIL,Yes,WAS,37:13,11,19,.579,0,...,6,9,3,3,1,3,2,31,26.8,33
15,17,16,MIL,Yes,POR,38:49,11,21,.524,0,...,10,16,6,1,3,4,5,33,28.4,33
16,18,17,MIL,No,MIA,39:30,11,16,.688,1,...,8,10,5,3,1,4,3,33,30.8,26
17,19,18,MIL,No,CHI,38:52,11,17,.647,0,...,8,14,5,2,5,5,5,26,27.1,32
18,20,19,MIL,Yes,ATL,36:19,14,20,.700,0,...,9,11,10,2,1,5,1,32,31.6,35
19,21,20,MIL,Yes,NYK,33:49,15,22,.682,1,...,5,8,10,3,0,4,3,35,32.0,37
20,22,21,MIL,Yes,IND,40:30,13,19,.684,0,...,9,10,2,0,2,1,3,37,32.1,32
21,23,22,MIL,Yes,CHI,40:57,9,13,.692,0,...,11,12,6,2,0,2,2,32,32.3,64
22,24,23,MIL,Yes,IND,37:13,20,28,.714,0,...,11,14,3,4,1,4,1,64,57.0,22
23,25,24,MIL,Yes,DET,25:47,7,9,.778,0,...,7,8,6,1,0,0,1,22,24.1,26
24,26,25,MIL,Yes,HOU,39:10,10,22,.455,1,...,11,17,3,0,0,6,3,26,14.6,11
25,27,26,MIL,Yes,SAS,33:36,4,12,.333,0,...,12,14,16,2,1,3,1,11,18.5,37
26,28,27,MIL,Yes,ORL,37:18,11,25,.440,0,...,8,10,6,0,2,5,4,37,25.1,28
27,29,28,MIL,No,NYK,32:21,11,17,.647,0,...,5,7,7,1,1,5,4,28,22.6,32
28,30,29,MIL,No,NYK,38:39,13,24,.542,1,...,8,13,6,1,2,2,4,32,27.7,32
29,31,30,MIL,No,BRK,30:27,10,12,.833,0,...,8,10,8,0,2,2,2,32,33.6,34
30,32,31,MIL,No,CLE,36:34,14,22,.636,0,...,14,16,5,1,0,3,2,34,30.1,30
31,33,32,MIL,Yes,IND,36:55,11,20,.550,0,...,15,18,11,1,2,4,3,30,30.7,26
32,34,33,MIL,No,IND,35:43,8,13,.615,1,...,11,11,8,3,1,3,2,26,27.3,44
33,35,34,MIL,No,SAS,39:30,19,28,.679,2,...,11,14,7,2,1,1,3,44,42.0,48
34,36,35,MIL,No,HOU,38:56,16,25,.640,1,...,14,17,2,0,1,2,4,48,39.3,0

## Data Seperation/Splitting

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
import pandas as pd

categorical_columns = ['Tm', 'Home', 'Opp', 'MP']

# Apply one-hot encoding to each categorical column
df_encoded = pd.get_dummies(df, columns=categorical_columns, drop_first=True)

# Separate features (X) and target variable (y)
X = df_encoded.drop("NextPTS", axis=1)
y = df_encoded['NextPTS']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

# Create and train the RandomForestRegressor
rf = RandomForestRegressor(random_state=42)
rf.fit(X_train, y_train)

# Predictions 
y_rf_train_pred = rf.predict(X_train)
y_rf_test_pred = rf.predict(X_test)

Apply model to make prediction

In [48]:
from sklearn.metrics import mean_squared_error, r2_score

rf_train_mse = mean_squared_error(y_train, y_rf_train_pred)
rf_train_r2 = r2_score(y_train, y_rf_train_pred)

rf_test_mse = mean_squared_error(y_test, y_rf_test_pred)
rf_test_r2 = r2_score(y_test, y_rf_test_pred)

In [49]:
rf_results = pd.DataFrame(["Random Forest", rf_train_mse, rf_train_r2, rf_test_mse, rf_test_r2]).transpose()
rf_results.columns = ["Method", "Training MSE", "Training R2", "Test MSE", "Test R2"]
rf_results

          Method Training MSE Training R2 Test MSE   Test R2
0  Random Forest    14.410918    0.878021  154.081  0.246209

## Actually Predicting

In [62]:
X_new = df
X_new = X_new.loc[[34]]   
X_new

,Rk,G,Tm,Home,Opp,MP,FG,FGA,FG%,3P,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,NextPTS
34,36,35,MIL,No,HOU,38:56,16,25,.640,1,...,14,17,2,0,1,2,4,48,39.3,0

In [68]:
# Apply one-hot encoding to the categorical columns in X_new
X_new_encoded = pd.get_dummies(X_new, columns=categorical_columns, drop_first=True)

# Ensure that the order of columns in X_new_encoded is consistent with the order used during training
X_new_encoded = X_new_encoded.reindex(columns=X.columns, fill_value=0)

# Make predictions using the trained model
next_game_predictions = rf.predict(X_new_encoded)

# Display or use the predictions as needed
print("Predicted Points for Next Game:", next_game_predictions)

Predicted Points for Next Game: [27.46]